[[constraint]]
  branch = "make-auth-provisioning-skipable"
  name = "github.com/docker/machine"
  source = "github.com/kubermatic/machine"

[[constraint]]
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/spf13/pflag"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.8.0"

[[constraint]]
  name = "github.com/kube-node/nodeset"
  branch = "henrik"
  source = "github.com/mrIncompetent/nodeset"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-5.0"
