version: 2
jobs:
  install-dependencies:
    docker:
      - image: golang:1.9
    working_directory: /go/src/github.com/kube-node/kube-machine
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure -vendor-only
      - persist_to_workspace:
          root: /go/src/github.com/kube-node/kube-machine
          paths:
            - .
  test:
    docker:
      - image: golang:1.9
    working_directory: /go/src/github.com/kube-node/kube-machine
    steps:
      - attach_workspace:
          at: .
      - run: go test -v $(go list ./... | grep -v /vendor/)
  build:
    docker:
      - image: golang:1.9
    working_directory: /go/src/github.com/kube-node/kube-machine
    steps:
      - attach_workspace:
          at: .
      - run: go build -o node-controller cmd/controller/main.go
      - store_artifacts:
          path: node-controller
          destination: node-controller
      - run: mkdir _output && mv node-controller _output/
      - persist_to_workspace:
          root: /go/src/github.com/kube-node/kube-machine
          paths:
            - .
  build-driver:
    docker:
      - image: golang:1.9
    working_directory: /go/src/github.com/docker/machine
    steps:
      - run:
          command: |
            git clone https://github.com/kubermatic/machine.git /go/src/github.com/docker/machine 
            make build
      - store_artifacts:
          path: bin/docker-machine
          destination: docker-machine
      - run: mkdir _driver && mv bin/docker-machine _driver/
      - persist_to_workspace:
          root: /go/src/github.com/docker/machine
          paths:
            - .
  push-hash:
    docker:
      - image: docker:stable
    working_directory: /go/src/github.com/kube-node/kube-machine
    steps:
      - run: apk update && apk add tar
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run: |
          docker build -t kubenode/kube-machine .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag kubenode/kube-machine kubenode/kube-machine:$CIRCLE_SHA1
          docker push kubenode/kube-machine:$CIRCLE_SHA1
  push-latest:
    docker:
      - image: docker:stable
    working_directory: /go/src/github.com/kube-node/kube-machine
    steps:
      - run: apk update && apk add tar
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run: |
          docker build -t kubenode/kube-machine .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag kubenode/kube-machine kubenode/kube-machine:latest
          docker push kubenode/kube-machine:latest
  push-release:
    docker:
      - image: docker:stable
    working_directory: /go/src/github.com/kube-node/kube-machine
    steps:
      - run: apk update && apk add tar
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run: |
          docker build -t kubenode/kube-machine .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag kubenode/kube-machine kubenode/kube-machine:$CIRCLE_TAG
          docker push kubenode/kube-machine:$CIRCLE_TAG
workflows:
  version: 2
  build_and_test:
    jobs:
      - install-dependencies:
          filters:
            tags:
              only: /v.*/
      - test:
          requires:
            - install-dependencies
          filters:
            tags:
              only: /v.*/
      - build-driver:
          requires:
            - build
          filters:
            tags:
              only: /v.*/
      - build:
          requires:
            - install-dependencies
          filters:
            tags:
              only: /v.*/
      - push-hash:
          requires:
            - build-driver
          filters:
            tags:
              only: /v.*/
      - push-latest:
          requires:
            - build-driver
          filters:
            branches:
              only:
                - master
            tags:
              only: /v.*/
      - push-release:
          requires:
            - build-driver
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
