apiVersion: "nodeset.k8s.io/v1alpha1"
kind: NodeClass
metadata:
  name: do-sfo1-2gb-coreos-stable
nodeController: kube-machine
config:
  dockerMachineFlags:
    digitalocean-access-token: "YOUR_DO_TOKEN"
    digitalocean-region: "sfo1"
    digitalocean-size: "2gb"
    digitalocean-ssh-user: "core"
    digitalocean-image: "coreos-stable"
  provider: "digitalocean"
  provisioning:
    users:
      - name: "apiserver"
        ssh_keys:
          - "ssh-rsa AAAAAAAA foo@bar.com"
        sudo: true
    commands:
      - "sudo systemctl daemon-reload"
      - "sudo systemctl enable docker && sudo systemctl restart docker"
      - "sudo systemctl start download-kubelet.service"
      - "sudo systemctl enable kubelet && sudo systemctl restart kubelet"
    files:
      - path: "/etc/kubernetes/bootstrap.kubeconfig"
        permissions: "0640"
        owner: "root"
        content: |-
          apiVersion: v1
          clusters:
          - cluster:
              certificate-authority-data: AAAAAAAAAAAAAAAAAA
              server: https://0.0.0.0:8443
            name: default
          contexts:
          - context:
              cluster: default
              user: default
            name: default
          current-context: default
          kind: Config
          preferences: {}
          users:
          - name: default
            user:
              token: TOKEN

      - path: "/etc/systemd/system/download-kubelet.service"
        permissions: "0640"
        owner: "root"
        content: |-
          [Unit]
          Description=Download Kubelet and requirements
          After=network.target

          [Service]
          Type=oneshot
          ExecStartPre=/usr/bin/mkdir -p /opt/bin /opt/cni/bin /etc/cni/net.d /var/run/kubernetes /var/lib/kubelet /etc/kubernetes/manifests /var/log/containers
          ExecStartPre=/bin/bash -c "/usr/bin/curl -L -o /tmp/cni-amd64.tgz https://github.com/containernetworking/cni/releases/download/v0.5.2/cni-amd64-v0.5.2.tgz && tar -xvf /tmp/cni-amd64.tgz -C /opt/cni/bin/"
          ExecStartPre=/usr/bin/curl -L -o /opt/bin/socat https://s3-eu-west-1.amazonaws.com/kubermatic/coreos/socat
          ExecStartPre=/usr/bin/chmod +x /opt/bin/socat
          ExecStartPre=/usr/bin/curl -L -o /opt/bin/kubelet https://storage.googleapis.com/kubernetes-release/release/v1.6.7/bin/linux/amd64/kubelet
          ExecStart=/usr/bin/chmod +x /opt/bin/kubelet
          RemainAfterExit=true

          [Install]
          WantedBy=multi-user.target

      - path: "/etc/systemd/system/kubelet.service"
        permissions: "0640"
        owner: "root"
        content: |-
          [Unit]
          Description=Kubelet
          After=network.target download-kubelet.service

          [Service]
          Restart=always
          RestartSec=10
          Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin"
          ExecStart=/opt/bin/kubelet \
            --api-servers=https://0.0.0.0:8443 \
            --container-runtime=docker \
            --allow-privileged=true \
            --pod-manifest-path=/etc/kubernetes/manifests \
            --cni-conf-dir=/etc/cni/net.d \
            --network-plugin=cni \
            --cluster-dns=10.10.10.10 \
            --cluster_domain=cluster.local \
            --kubeconfig=/etc/kubernetes/kubeconfig \
            --experimental-bootstrap-kubeconfig=/etc/kubernetes/bootstrap.kubeconfig \
            --cert-dir=/etc/kubernetes/

          [Install]
          WantedBy=multi-user.target
